### ISSUE TITLE
Use original SOMFY RTS USB Device (29€) 

### ISSUE THREAD

**Issue by sined35** [mwraith/homebridge-somfi-blinds#1]
Hello, i have seen that Somfy as released an USB antenna with RTS protocol.
 (https://www.leroymerlin.fr/produits/chauffage-plomberie/chauffage-electrique/radiateur-electrique/pack-connecte-pour-radiateur-electrique/cle-extension-somfy-rts-pour-box-enki-82292229.html)
Can you think you can support/add this device ? 
It would be easier to integrate on Homebridge, for those (like me) who are not keen in electronic modifications.

**Comment by bosu1787** [comment]
the plugin give me an error ..

Error: Cannot find module '@babel/types'

**Comment by bosu1787** [comment]
is not so hard to do it i can make one for you and send it via post :)

**Comment by bosu1787** [comment]
> Hello, i have seen that Somfy as released an USB antenna with RTS protocol. (https://www.leroymerlin.fr/produits/chauffage-plomberie/chauffage-electrique/radiateur-electrique/pack-connecte-pour-radiateur-electrique/cle-extension-somfy-rts-pour-box-enki-82292229.html) Can you think you can support/add this device ? It would be easier to integrate on Homebridge, for those (like me) who are not keen in electronic modifications.

is not so hard to do it i can make one for you and send it via post :)

**Comment by mwraith** [comment]
Hi @sined35. Interesting that it's available as a USB antenna, but no I'm sorry it's not within the scope of this project to support it.

I would say that it was my first time with raspberry pis or electronics etc. It was not so difficult. Give it a go and I think it will work out ok. If you have any questions let me know and I can give some more info.
