### ISSUE TITLE
Plugin doesn't seem to do anything, while the RPI-RTS works perfectly fine

### ISSUE THREAD

**Issue by Peet-B** [mwraith/homebridge-somfi-blinds#10]
I would love the functionality of this plugin since the RPI-RTS plugin with its 4 buttons drives me nuts, also when rebooting the bridge the labels of all 4 buttons are the same, so I have to take 15 minutes to rename every single button again... 

That being said. RPI-RTS is running without any issues, though this plugin seems to do absolutely nothing at all... Using homebridge via Hoobs, don't know if that changes things.

The terminal says that it actually detects the 2 accessories I added, but they are nowhere to be found?
<img width="699" alt="Screenshot 2023-07-11 at 14 07 49" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/55404445/0558c492-d7c2-43bf-a4ba-548c1d75fb4f">

**Comment by mwraith** [comment]
Can you post your Homebridge Config?

And can you try running Homebridge in Debug mode and see if anything useful is logged?

**Comment by Peet-B** [comment]
This is my config for the 2 items

<img width="573" alt="Screenshot 2023-07-27 at 12 28 49" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/55404445/74b904db-8310-4ad5-b908-2d5001651d1d">

This is the debug log I get from the bridge
<img width="882" alt="Screenshot 2023-07-27 at 12 29 06" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/55404445/a9f95ce3-7e8f-4217-9ab8-492b21fc5687">

Seems to me that nothing weird is happening. Weird since the RPI-RTS plugin is working fine

**Comment by Peet-B** [comment]
Fixed it myself. Appeared to be some weird Hoobs not being able to run as root. Opted for a clean homebridge installation instead and everything seems to work fine now.
