### ISSUE TITLE
can't pair with blinds

### ISSUE THREAD

**Issue by Nicode70** [mwraith/homebridge-somfi-blinds#12]
I was previously using wibberryd plugging and it was working just fine. I've juste upgraded my raspberry from pi 3b to 4b.
I've change from the wibberyd plugin to yours.
user is root
homebridge version: V1.7.0
node version v20.9.0 
os version Raspbian GNU/Linux Bullseye (11)

I've set the accessory, it appears in HomeKit as a group of 5 (for switches and a blind). But I can't pair the blind because the switches just turn themselves off instantly. and they are all called by the same name so I don't know wich on is the prog button.

Could you please help me?

**Comment by mwraith** [comment]
Hi @Nicode70. It’s odd that they show with the same name, the buttons and names should correspond to the buttons on the remote (Up, Down, My, Prog) when in Admin mode.

Is it the same when looking at the accessory via the Homebridge web UI too?

**Comment by Nicode70** [comment]
in homebridge gui, they are named:
store up; store down; store my; store prog.

in HomeKit they are all just called store
![IMG_2688](https://github.com/mwraith/homebridge-somfi-blinds/assets/16838672/46c1dfa8-ae36-4b0b-9fc8-41f55dcd7c4d)
 
also, I just can't turn one on. it instantly revert back to off. I have no mean to paire the blind.

**Comment by Nicode70** [comment]
here is what my edited homebridge file looks like
<img width="558" alt="Capture d’écran 2023-11-21 à 18 12 12" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/16838672/8269b9df-d5b7-46b3-9b9f-6a0bafbe3978">
and the config in homebridge:
<img width="298" alt="Capture d’écran 2023-11-21 à 18 14 33" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/16838672/65cdf9a7-a763-42ca-a078-8cdbb07a5952">

What did I do wrong?

**Comment by mwraith** [comment]
@Nicode70 Homebridge UI is being displayed as I’d expect. In HomeKit it looks like for some reason it is trimming the command from the name. 

I can try to reproduce it, but in the interim you should be able to pair it by sending the commands from the Homebridge UI. Once paired you can then switch off the admin mode so HomeKit will anyway be ok.

**Comment by Nicode70** [comment]
Thank you very much @mwraith. But even from the homebridge ui I can’t switch any of the switches on. 
<img width="851" alt="Capture d’écran 2023-11-21 à 18 42 08" src="https://github.com/mwraith/homebridge-somfi-blinds/assets/16838672/3f51eb8a-11b4-42ae-8586-ecc4a1874554">

**Comment by mwraith** [comment]
@Nicode70 So for Up/Down/My/Prog the switches don’t stay ‘on’. When you switch them on it will send the correct signal for the button and then immediately switch it back to off. It’s just trying to simulate a button press on the real remote where it’s stateless.

So basically if you follow the pairing instructions and for step 4 press Prog within Homebridge it should register.

If it does not then it is more likely to be an issue sending the signal or with reception.

**Comment by Nicode70** [comment]
I've tried to pair once again with a single click on the prog button of the homebridge UI.
changed config back to  "adminMode": false,
restarted homebridge
tried to open the blinds and got this message in the logs: 

[21/11/2023, 20:18:29] [homebridge-somfi-blinds] This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: pigpio error -1 in gpioInitialise. See https://homebridge.io/w/JtMGR for more info.
1034224, 2, 1
2023-11-21 20:18:32 initInitialise: Can't lock /var/run/pigpio.pid

**Comment by mwraith** [comment]
@Nicode70 That would mean another process is already running using the transmitter. You would need to find the other process and shut it down. See https://raspberrypi.stackexchange.com/questions/38644/pigpio-cant-lock-var-run-pigpio-pid

**Comment by Nicode70** [comment]
It worked! Thank you very much.
