### ISSUE TITLE
error after update homebridge update

### ISSUE THREAD

**Issue by bosu1787** [mwraith/homebridge-somfi-blinds#4]
[homebridge-somfi-blinds] This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: pigpio error -1 in gpioInitialise. See https://git.io/JtMGR for more info.

**Comment by mwraith** [comment]
Can you switch homebridge debug logs on and see if there are any other errors that might help narrow it down?

Maybe try uninstall and reinstall plugin (take care to backup & restore config file).

Also i saw https://github.com/wibberryd/homebridge-rpi-rts/issues/5 mention the same error. There are some comments in this thread you might try.

**Comment by bosu1787** [comment]
2022-04-27 07:05:59 initInitialise: bind to port 8888 failed (Address already in use)

i have ebusd installed which use 8888 port so i think this is causing this issue

**Comment by bosu1787** [comment]
yeap i have stoped ebusd and its working :) can i change the port ?

**Comment by mwraith** [comment]
Slow reply, but it's defined in pigpio library. From the docs it sounds like you could change port with `pigpiod -p 1234`
