### ISSUE TITLE
Path to homebridge service changed

### ISSUE THREAD

**Issue by RealHaltewunsch** [mwraith/homebridge-somfi-blinds#5]
The homebridge service moved in early May from **/etc/systemd/system/homebridge.service** to **/etc/systemd/system/multi-user.target.wants/homebridge.service**.
In addition to that, the file **/etc/default/homebridge** moved, but I have not found it yet.

**Comment by mwraith** [comment]
@RealHaltewunsch I still haven't encountered problems though I've upgraded. Did you work this out eventually?

For me /etc/systemd/system/multi-user.target.wants/homebridge.service is just a symlink to /etc/systemd/system/homebridge.service so I don't think it should affect the setup instructions.

**Comment by Louison-B** [comment]
Solution here :
https://github.com/wibberryd/homebridge-rpi-rts/issues/22#issue-1295260741

**Comment by mwraith** [comment]
Thanks @Louison-B! I've updated the readme
