### ISSUE TITLE
it is possible use pigpio-client insted of pigpio?

### ISSUE THREAD

**Issue by bosu1787** [mwraith/homebridge-somfi-blinds#8]
hi im moving my hombridge to my ubuntu server so no gpio in my server what im trying to do is put an rpi 0 on usb and use the gpios from that but like that only pigpio-client is working. so i need your help.thanks

**Comment by mwraith** [comment]
Hi @bosu1787.

Everything related to sending of the signal is within the file src/RpiGpioRts.js so this is the file you'll need to rewrite to work with pigpio-client. 

Looking at the documentation the command names are slightly different, but I think it's a very similar concept and possible. The commands to initialise and send the signal are slightly different in sendCommand. Also the structure of the waveform which is constructed in getWaveform looks to be different. With pigpio it's specified as JSON like `{ gpioOn: outPin, gpioOff: 0, usDelay: 1000 }` but with pigpio-client it looks to be an array like `[1, 0, 1000]`. It does not look too different.

Let me know how you get on with it. If you hit any issues, share your code (maybe as a fork) and I'll try to help where I can.

Mark

**Comment by bosu1787** [comment]
thank you @mwraith 

im not very good at coding :) but i will try.

thank you.
